<a href="https://colab.research.google.com/github/SumathiGit/NLP-2/blob/main/Text_Classification(Movie_Review).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("moviereviews.tsv", sep='\t')
df

label                                             review
0      neg  how do films like mouse hunt get into theatres...
1      neg  some talented actresses are blessed with a dem...
2      pos  this has been an extraordinary year for austra...
3      pos  according to hollywood movies made in last few...
4      neg  my first press screening of 1998 and already i...
...    ...                                                ...
1995   pos  i like movies with albert brooks , and i reall...
1996   pos  it might surprise some to know that joel and e...
1997   pos  the verdict : spine-chilling drama from horror...
1998   pos  i want to correct what i wrote in a former ret...
1999   pos  a couple of months ago , when i first download...

[2000 rows x 2 columns]

In [ ]:
#print(df['review'][2])

In [4]:
df.isnull().sum() #Seems like we have some missing reviews

label      0
review    35
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.isnull().sum() 

label     0
review    0
dtype: int64

In [7]:
len(df)

1965

In [8]:
#Double check if there any other null values
blanks = []  # start with an empty list

for i,lb,rv in df.itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
        
print(len(blanks), 'blanks: ', blanks)

27 blanks:  [57, 71, 147, 151, 283, 307, 313, 323, 343, 351, 427, 501, 633, 675, 815, 851, 977, 1079, 1299, 1455, 1493, 1525, 1531, 1763, 1851, 1905, 1993]


In [9]:
df.drop(blanks, inplace=True)

len(df)

1938

In [10]:
df['label'].value_counts()

pos    969
neg    969
Name: label, dtype: int64

In [13]:
#Split the data into train & test sets:
from sklearn.model_selection import train_test_split

X = df['review']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
#Building a Pipeline to Vectorize the data, train and also fit the model

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

# Naïve Bayes:(First PIPELINE)
text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),
])

# Linear SVC:(SECOND PIPELINE)
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

In [15]:
#Passing thr training data into First pipeline
text_clf_nb.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [16]:
predictions = text_clf_nb.predict(X_test)

In [17]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[287  21]
 [130 202]]


In [18]:
print(metrics.accuracy_score(y_test,predictions)) #WE got 76% accuracy

0.7640625


In [ ]:
#PAssing the training data into second pipeline

In [19]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [21]:
predictions = text_clf_lsvc.predict(X_test)

In [22]:
print(metrics.confusion_matrix(y_test,predictions))

[[259  49]
 [ 49 283]]


In [23]:
print(metrics.accuracy_score(y_test,predictions)) #And now we got 84 % of accuracy

0.846875


In [39]:
#Testing
myreview = "I saw this movie yesterday and guess what it's such an terrible movie ,The songs were awful, not good"

In [40]:
print(text_clf_lsvc.predict([myreview]))

['neg']


In [ ]:
"""Adding Stopwords to CountVectorizer"""

In [30]:
from sklearn.feature_extraction import text
print(text.ENGLISH_STOP_WORDS)

frozenset({'eleven', 'con', 'somehow', 'per', 'its', 'find', 'hereby', 'behind', 'few', 'here', 'now', 'side', 'there', 'very', 'wherever', 'eight', 'name', 'same', 'until', 'herself', 'even', 'whereby', 'nobody', 'he', 'without', 'almost', 'get', 'never', 'fifteen', 'indeed', 'co', 'hereupon', 'hereafter', 'therefore', 'whenever', 'another', 'up', 'ltd', 'mostly', 'others', 'nine', 'only', 'all', 'full', 'thus', 're', 'together', 'becomes', 'part', 'our', 'as', 'beside', 'keep', 'at', 'their', 'back', 'cant', 'put', 'onto', 'who', 'ourselves', 'whether', 'why', 'any', 'within', 'over', 'thereupon', 'de', 'ever', 'am', 'among', 'nowhere', 'own', 'throughout', 'two', 'the', 'every', 'detail', 'whom', 'towards', 'you', 'twelve', 'around', 'besides', 'when', 'give', 'next', 'while', 'forty', 'cry', 'on', 'me', 'from', 'your', 'be', 'after', 'itself', 'ie', 'but', 'too', 'therein', 'several', 'front', 'thru', 'they', 'along', 'etc', 'whole', 'us', 'please', 'was', 'yourselves', 'in', 'of',

In [32]:
stopwords = ['a', 'about', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'can', \
             'even', 'ever', 'for', 'from', 'get', 'had', 'has', 'have', 'he', 'her', 'hers', 'his', \
             'how', 'i', 'if', 'in', 'into', 'is', 'it', 'its', 'just', 'me', 'my', 'of', 'on', 'or', \
             'see', 'seen', 'she', 'so', 'than', 'that', 'the', 'their', 'there', 'they', 'this', \
             'to', 'was', 'we', 'were', 'what', 'when', 'which', 'who', 'will', 'with', 'you']

In [33]:
text_clf_lsvc1 = Pipeline([('tfidf', TfidfVectorizer(stop_words=stopwords)),
                     ('clf', LinearSVC()),
])

In [34]:
text_clf_lsvc1.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=['a', 'about', 'an', 'and', 'are',
                                             'as', 'at', 'be', 'been', 'but',...
                                             'how', 'i', 'if', 'in', 'into',
                                             'is', ...],
                                 strip_accents=None, sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer

In [35]:
predictions = text_clf_lsvc1.predict(X_test)

In [36]:
print(metrics.confusion_matrix(y_test,predictions))

[[256  52]
 [ 48 284]]


In [37]:
print(metrics.accuracy_score(y_test,predictions))

0.84375


In [41]:
print(text_clf_lsvc1.predict([myreview]))

['neg']


In [44]:
myrev = "A movie I really wanted to love was terrible. \
I'm sure the producers had the best intentions, but the execution was lacking."

In [45]:
print(text_clf_lsvc1.predict([myrev]))

['neg']
